src/Entity/Command.php
<?php

namespace App\Entity;

use App\Repository\CommandRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommandRepository::class)]
class Command
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'commands')]
    #[ORM\JoinColumn(nullable: false)]
    private $user;

    #[ORM\Column(type: 'datetime')]
    private $date;

    #[ORM\Column(type: 'string', length: 255)]
    private $status;

    #[ORM\OneToMany(mappedBy: 'command', targetEntity: CommandLine::class, orphanRemoval: true)]
    private $commandLines;

    public function __construct()
    {
        $this->commandLines = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    /**
     * @return Collection|CommandLine[]
     */
    public function getCommandLines(): Collection
    {
        return $this->commandLines;
    }

    public function addCommandLine(CommandLine $commandLine): self
    {
        if (!$this->commandLines->contains($commandLine)) {
            $this->commandLines[] = $commandLine;
            $commandLine->setCommand($this);
        }

        return $this;
    }

    public function removeCommandLine(CommandLine $commandLine): self
    {
        if ($this->commandLines->removeElement($commandLine)) {
            // set the owning side to null (unless already changed)
            if ($commandLine->getCommand() === $this) {
                $commandLine->setCommand(null);
            }
        }

        return $this;
    }
    public function getTotal(): float
    {
        $sum = 0.0;
        foreach ($this->getCommandLines() as $cl) {
            $sum += $cl->getPrice();
        }
        return $sum;
    }
}

src/Form/CommandType.php
<?php

namespace App\Form;

use App\Entity\Command;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CommandType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('date')
            ->add('status')
            ->add('user')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Command::class,
        ]);
    }
}

src/Controller/CommandController.php
<?php

namespace App\Controller;

use App\Entity\Command;
use App\Form\CommandType;
use App\Repository\CommandRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/{_locale}/command', requirements: ['_locale' => '%app.supported_locales%'])]
class CommandController extends AbstractController
{
    #[Route('/', name: 'command_index', methods: ['GET'])]
    public function index(CommandRepository $commandRepository): Response
    {
        return $this->render('command/index.html.twig', [
            'commands' => $commandRepository->findAll(),
        ]);
    }

    #[Route('/{id}', name: 'command_show', methods: ['GET'])]
    public function show(Command $command): Response
    {
        return $this->render('command/show.html.twig', [
            'command' => $command,
        ]);
    }

}

templates/command/index.html.twig
{% extends "common/base.html.twig" %}
{% block title %}My commands
{% endblock %}
{% block body %}
	<script src="{{ asset("js/command.js") }}"></script>
	<style src="{{ asset("style/command.css") }}"></style>
	<h1>All your commands:</h1>
	<table class="table">
		<thead>
			<tr>
				<th>Id</th>
				<th>Date</th>
				<th>Total</th>
				<th>Status</th>
				<th>Actions</th>
			</tr>
		</thead>
		<tbody>
			{% for command in commands %}
				<tr style="border: 2px solid black;">
					<td>{{ command.id }}</td>
					<td>{{ command.date ? command.date|date('Y-m-d H:i:s') : '' }}</td>
					<td>{{ command.total }}€</td>
					<td>{{ command.status }}</td>
					<td>
						<!-- Button trigger modal -->
						<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modal{{command.id}}">
							See
							<i class="bi bi-arrows-angle-expand"></i>
						</button>

						<!-- Modal -->
						<div class="modal fade" id="modal{{command.id}}" tabindex="-1" role="dialog" aria-labelledby="modalLabel{{command.id}}" aria-hidden="true">
							<div class="modal-dialog" role="document">
								<div class="modal-content">
									<div class="modal-header">
										<h5 class="modal-title" id="modalLabel{{command.id}}">Command: {{command.id}}</h5>
										<button type="button" class="close" data-dismiss="modal" aria-label="Close">
											<span aria-hidden="true">&times;</span>
										</button>
									</div>
									<div class="modal-body">{{ include('command_line/index.html.twig', {'command_lines': command.commandlines })}}
									<div><strong>Total: {{command.total}}€</strong></div>
								</div>
								<div class="modal-footer">
									<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
									<button type="button" class="btn btn-light" onclick="location.href='{{ path('user_command', {'id': command.id}) }}'">Details</button>
								</div>
							</div>
						</div>
					</td>
				</tr>
			</td>
		</tbody>
	</tr>
</div></tbody></td></tr>{% else %}<tr><td colspan="4">no records found</td></tr>{% endfor %}</tbody></tbody></table>{% endblock %}

templates/command/show.html.twig
{{if nonav}} {{else}}
		{% extends "common/base.html.twig" %} {{endif}}
{% block body %}
	<h1>
		Command: {{ command.date ? command.date|date('Y-m-d H:i:s') : '' }}
	</h1>
	<table class="table">
		<tbody>
			<tr>
				<th>Id</th>
				<td>{{ command.id }}</td>
			</tr>
			<tr>
				<th>Date</th>
				<td>{{ command.date ? command.date|date('Y-m-d H:i:s') : '' }}</td>
			</tr>
			<tr>
				<th>Status</th>
				<td>{{ command.status }}</td>
			</tr>
			<tr>
				<th>Total</th>
				<td>{{ command.total }}€</td>
			</tr>
		</tbody>
	</table>
	<h2>Products:
	</h2> {{ include('command_line/index.html.twig', {'commandlines': command.commandlines}) }}

{% endblock %}